apiVersion: v1
kind: Deployment  
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
     containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-username
          - name: USER_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-configs
                key: mongo-url

      # visit the webapp service:
      # kubectl port-forward svc/webapp 3001:3000
      # the service is available in localhost:3001
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
