{{ if .Values.provisioners.workers.enabled }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: workers
spec:
  consolidation: #Consolidation or Ttl are the options, consolidation will ensure that consumption of resources is always maximized
    enabled: true
  taints:
    - key: workers
      value: 'true'
      effect: NoExecute
  requirements:
    - key: workers
      operator: Exists
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: [c]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand", "spot"]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64
  limits:
    resources:
      cpu: '600'
      memory: 1200Gi
  providerRef:
    name: workers
{{ end }}
