{{ if .Values.provisioners.tasks.enabled }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: tasks
spec:
  # consolidation:
  #   enabled: true
  ttlSecondsAfterEmpty: 30
  taints:
    - key: tasks
      value: 'true'
      effect: NoExecute
  requirements:
    - key: tasks
      operator: Exists
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: [t]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64
  limits:
    resources:
      cpu: '30'
      memory: 200Gi
  providerRef:
    name: default
{{ end }}
