{{ if .Values.provisioners.default.enabled }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # consolidation:
  #   enabled: true
  ttlSecondsAfterEmpty: 60
  requirements:
    - key: default
      operator: Exists
    # - key: karpenter.k8s.aws/instance-category
    #   operator: In
    #   values: [c, m]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
    - key: kubernetes.io/os	
      operator: In	
      values:	
        - linux	
    - key: kubernetes.io/arch	
      operator: In	
      values:	
        - amd64
  limits:
    resources:
      cpu: '40'
      memory: 200Gi
  providerRef:
    name: default
{{ end }}
